services:
  php-fpm:
    build:
      context: etc/devel/docker/php-fpm
    image: app/php-fpm
    container_name: app.php-fpm
    volumes:
      - ".:/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  nginx:
    build:
      context: etc/devel/docker/nginx
    image: app/nginx
    container_name: app.nginx
    volumes:
      - "./assets:/var/www/"
    ports:
      - 80:80

  redis:
    build:
      context: etc/devel/docker/redis
    image: app/redis
    container_name: app.redis
    ports:
      - 6379:6379

  mariadb:
    build:
      context: etc/devel/docker/mariadb
    image: app/mariadb
    container_name: app.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306

  swagger_ui:
    environment:
      - SWAGGER_JSON=./assets/docs/users-api.yml
      - API_URL=http://localhost/docs/users-api.yml
    image: swaggerapi/swagger-ui
    container_name: app.swagger
    volumes:
      - "./assets/docs/users-api.yml:/usr/share/nginx/html/users-api.yml"
    ports:
      - 8080:8080
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
